version: '3'

networks:
  mynetwork:
    driver: bridge
services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    ports:
      - "16686:16686"
      - "4318:4318"
    container_name: jaeger
    environment:
      - LOG_LEVEL=debug
    networks:
      - mynetwork
  infinispan-lon-1:
    image: quay.io/infinispan-test/server:main
    ports:
      - "11222:11222"
    container_name: infinispan-lon-1
    environment:
      USER: admin
      PASS: password
    volumes:
      - ./infinispan-tracing-configuration-server.yaml:/user-config/infinispan-tracing-configuration-server.yaml
    command: -c infinispan-xsite.xml -c /user-config/infinispan-tracing-configuration-server.yaml -Dinfinispan.site.name=LON -Djgroups.mcast_port=46656
  infinispan-lon-2:
    image: quay.io/infinispan-test/server:main
    ports:
      - "11223:11222"
    container_name: infinispan-2
    environment:
      USER: admin
      PASS: password
    volumes:
      - ./infinispan-tracing-configuration-server.yaml:/user-config/infinispan-tracing-configuration-server.yaml
    command: -c infinispan-xsite.xml -c /user-config/infinispan-tracing-configuration-server.yaml -Dinfinispan.site.name=LON -Djgroups.mcast_port=46656
  infinispan-lon-3:
    image: quay.io/infinispan-test/server:main
    ports:
      - "11224:11222"
    container_name: infinispan-3
    environment:
      USER: admin
      PASS: password
    volumes:
      - ./infinispan-tracing-configuration-server.yaml:/user-config/infinispan-tracing-configuration-server.yaml
    command: -c infinispan-xsite.xml -c /user-config/infinispan-tracing-configuration-server.yaml -Dinfinispan.site.name=LON -Djgroups.mcast_port=46656
    networks:
      - mynetwork
  infinispan-nyc:
    image: quay.io/infinispan-test/server:main
    ports:
      - "31222:11222"
    container_name: infinispan-nyc
    environment:
      USER: admin
      PASS: password
    volumes:
      - ./infinispan-tracing-configuration-server.yaml:/user-config/infinispan-tracing-configuration-server.yaml
    command: -c infinispan-xsite.xml -c /user-config/infinispan-tracing-configuration-server.yaml -Dinfinispan.site.name=NYC -Djgroups.mcast_port=56656
